execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @e[r=1] remove dest20
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @e[r=1] remove dest19
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @e[r=1] remove dest18
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @e[r=1] remove dest17
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @e[r=1] remove dest16
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @e[r=1] remove dest15
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @e[r=1] remove dest14
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @e[r=1] remove dest13
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @e[r=1] remove dest12
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @e[r=1] remove dest11
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @e[r=1] remove dest10
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @e[r=1] remove dest9
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @e[r=1] remove dest8
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @e[r=1] remove dest7
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @e[r=1] remove dest6
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @e[r=1] remove dest5
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @e[r=1] remove dest4
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @e[r=1] remove dest3
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @e[r=1] remove dest2
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @e[r=1] add dest1 