execute as @s[tag=dest20] at @s run tag @e[r=1] add destreset
execute as @s[tag=dest20] at @s run tag @e[r=1] remove dest20
execute as @s[tag=dest19] at @s run tag @e[r=1] add dest20
execute as @s[tag=dest19] at @s run tag @e[r=1] remove dest19
execute as @s[tag=dest18] at @s run tag @e[r=1] add dest19
execute as @s[tag=dest18] at @s run tag @e[r=1] remove dest18
execute as @s[tag=dest17] at @s run tag @e[r=1] add dest18
execute as @s[tag=dest17] at @s run tag @e[r=1] remove dest17
execute as @s[tag=dest16] at @s run tag @e[r=1] add dest17
execute as @s[tag=dest16] at @s run tag @e[r=1] remove dest16
execute as @s[tag=dest15] at @s run tag @e[r=1] add dest16
execute as @s[tag=dest15] at @s run tag @e[r=1] remove dest15
execute as @s[tag=dest14] at @s run tag @e[r=1] add dest15
execute as @s[tag=dest14] at @s run tag @e[r=1] remove dest14
execute as @s[tag=dest13] at @s run tag @e[r=1] add dest14
execute as @s[tag=dest13] at @s run tag @e[r=1] remove dest13
execute as @s[tag=dest12] at @s run tag @e[r=1] add dest13
execute as @s[tag=dest12] at @s run tag @e[r=1] remove dest12
execute as @s[tag=dest11] at @s run tag @e[r=1] add dest12
execute as @s[tag=dest11] at @s run tag @e[r=1] remove dest11
execute as @s[tag=dest10] at @s run tag @e[r=1] add dest11
execute as @s[tag=dest10] at @s run tag @e[r=1] remove dest10
execute as @s[tag=dest9] at @s run tag @e[r=1] add dest10
execute as @s[tag=dest9] at @s run tag @e[r=1] remove dest9
execute as @s[tag=dest8] at @s run tag @e[r=1] add dest9
execute as @s[tag=dest8] at @s run tag @e[r=1] remove dest8
execute as @s[tag=dest7] at @s run tag @e[r=1] add dest8
execute as @s[tag=dest7] at @s run tag @e[r=1] remove dest7
execute as @s[tag=dest6] at @s run tag @e[r=1] add dest7
execute as @s[tag=dest6] at @s run tag @e[r=1] remove dest6
execute as @s[tag=dest5] at @s run tag @e[r=1] add dest6
execute as @s[tag=dest5] at @s run tag @e[r=1] remove dest5
execute as @s[tag=dest4] at @s run tag @e[r=1] add dest5
execute as @s[tag=dest4] at @s run tag @e[r=1] remove dest4
execute as @s[tag=dest3] at @s run tag @e[r=1] add dest4
execute as @s[tag=dest3] at @s run tag @e[r=1] remove dest3
execute as @s[tag=dest2] at @s run tag @e[r=1] add dest3
execute as @s[tag=dest2] at @s run tag @e[r=1] remove dest2
execute as @s[tag=dest1] at @s run tag @e[r=1] add dest2
execute as @s[tag=dest1] at @s run tag @e[r=1] remove dest1
execute as @s[tag=destreset] at @s run tag @e[r=1] add dest1
execute as @s[tag=destreset] at @s run tag @e[r=1] remove destreset