execute as @s[tag=voltage_2] at @s run tag @e[tag=body,r=2] add voltage_off
execute as @s[tag=voltage_2] at @s run tag @s add voltage_off
execute as @s[tag=voltage_2] at @s run tag @e[tag=body,r=2] remove voltage_2
execute as @s[tag=voltage_2] at @s run tag @s remove voltage_2
execute as @s[tag=voltage_1] at @s run tag @e[tag=body,r=2] add voltage_2
execute as @s[tag=voltage_1] at @s run tag @s add voltage_2
execute as @s[tag=voltage_1] at @s run tag @e[tag=body,r=2] remove voltage_1
execute as @s[tag=voltage_1] at @s run tag @s remove voltage_1
execute as @s[tag=voltage_0] at @s run tag @e[tag=body,r=2] add voltage_1
execute as @s[tag=voltage_0] at @s run tag @s add voltage_1
execute as @s[tag=voltage_0] at @s run tag @e[tag=body,r=2] remove voltage_0
execute as @s[tag=voltage_0] at @s run tag @s remove voltage_0
execute as @s[tag=voltage_off] at @s run tag @e[tag=body,r=2] add voltage_0
execute as @s[tag=voltage_off] at @s run tag @s add voltage_0
execute as @s[tag=voltage_off] at @s run tag @e[tag=body,r=2] remove voltage_off  
execute as @s[tag=voltage_off] at @s run tag @s remove voltage_off
execute as @s[tag=!voltage_0,tag=!voltage_1,tag=!voltage_2] at @s run tag @e[tag=body,r=2] add voltage_1
execute as @s[tag=!voltage_0,tag=!voltage_1,tag=!voltage_2] at @s run tag @s add voltage_1