execute as @e[type=tcmb:tcmb_car,c=1] at @s run event entity @s[tag=eb] b7
execute as @e[type=tcmb:tcmb_car,c=1] at @s run event entity @s[tag=b7] b6
execute as @e[type=tcmb:tcmb_car,c=1] at @s run event entity @s[tag=b6] b5
execute as @e[type=tcmb:tcmb_car,c=1] at @s run event entity @s[tag=b5] b4
execute as @e[type=tcmb:tcmb_car,c=1] at @s run event entity @s[tag=b4] b3
execute as @e[type=tcmb:tcmb_car,c=1] at @s run event entity @s[tag=b3] b2
execute as @e[type=tcmb:tcmb_car,c=1] at @s run event entity @s[tag=b2] b1
execute as @e[type=tcmb:tcmb_car,c=1] at @s run event entity @s[tag=b1] n
execute as @e[type=tcmb:tcmb_car,c=1] at @s run event entity @s[tag=n] p1
execute as @e[type=tcmb:tcmb_car,c=1] at @s run event entity @s[tag=p1] p2
execute as @e[type=tcmb:tcmb_car,c=1] at @s run event entity @s[tag=p2] p3
execute as @e[type=tcmb:tcmb_car,c=1] at @s run event entity @s[tag=p3] p4
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @s[tag=!open_all,tag=!open_a,tag=!open_oneman_a,tag=!open_b,tag=!open_oneman_b] remove stopping