execute as @e[type=tcmb:tcmb_car,c=1] at @s run event entity @s[tag=b7] eb
execute as @e[type=tcmb:tcmb_car,c=1] at @s run event entity @s[tag=b6] b7
execute as @e[type=tcmb:tcmb_car,c=1] at @s run event entity @s[tag=b5] b6
execute as @e[type=tcmb:tcmb_car,c=1] at @s run event entity @s[tag=b4] b5
execute as @e[type=tcmb:tcmb_car,c=1] at @s run event entity @s[tag=b3] b4
execute as @e[type=tcmb:tcmb_car,c=1] at @s run event entity @s[tag=b2] b3
execute as @e[type=tcmb:tcmb_car,c=1] at @s run event entity @s[tag=b1] b2
execute as @e[type=tcmb:tcmb_car,c=1] at @s run event entity @s[tag=n] b1
execute as @e[type=tcmb:tcmb_car,c=1] at @s run event entity @s[tag=p1] n
execute as @e[type=tcmb:tcmb_car,c=1] at @s run event entity @s[tag=p2] p1
execute as @e[type=tcmb:tcmb_car,c=1] at @s run event entity @s[tag=p3] p2
execute as @e[type=tcmb:tcmb_car,c=1] at @s run event entity @s[tag=p4] p3