execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @s[tag=seat8] add seatrs
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @s[tag=seat8] remove seat8
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @s[tag=seat7] add seat8
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @s[tag=seat7] remove seat7
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @s[tag=seat6] add seat7
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @s[tag=seat6] remove seat6
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @s[tag=seat5] add seat6
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @s[tag=seat5] remove seat5
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @s[tag=seat4] add seat5
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @s[tag=seat4] remove seat4
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @s[tag=seat3] add seat4
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @s[tag=seat3] remove seat3
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @s[tag=seat2] add seat3
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @s[tag=seat2] remove seat2
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @s[tag=seat1] add seat2
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @s[tag=seat1] remove seat1
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @s[tag=seatrs] add seat1
execute as @e[type=tcmb:tcmb_car,c=1] at @s run tag @s[tag=seatrs] remove seatrs
execute as @e[type=tcmb:tcmb_car,c=1,tag=seat1] at @s run event entity @e[tag=body,r=2] seat1
execute as @e[type=tcmb:tcmb_car,c=1,tag=seat2] at @s run event entity @e[tag=body,r=2] seat2
execute as @e[type=tcmb:tcmb_car,c=1,tag=seat3] at @s run event entity @e[tag=body,r=2] seat3
execute as @e[type=tcmb:tcmb_car,c=1,tag=seat4] at @s run event entity @e[tag=body,r=2] seat4
execute as @e[type=tcmb:tcmb_car,c=1,tag=seat5] at @s run event entity @e[tag=body,r=2] seat5
execute as @e[type=tcmb:tcmb_car,c=1,tag=seat6] at @s run event entity @e[tag=body,r=2] seat6
execute as @e[type=tcmb:tcmb_car,c=1,tag=seat7] at @s run event entity @e[tag=body,r=2] seat7
execute as @e[type=tcmb:tcmb_car,c=1,tag=seat8] at @s run event entity @e[tag=body,r=2] seat8