execute as @s[type=tcmb:tcmb_car,tag=eb,tag=!backward,scores={speed=108..109}] at @s run summon tcmb:tcmb_starter ^1^^
execute as @s[type=tcmb:tcmb_car,tag=b7,tag=!backward,scores={speed=108..109}] at @s run summon tcmb:tcmb_starter ^1^^
execute as @s[type=tcmb:tcmb_car,tag=b6,tag=!backward,scores={speed=108..109}] at @s run summon tcmb:tcmb_starter ^1^^
execute as @s[type=tcmb:tcmb_car,tag=b5,tag=!backward,scores={speed=108..109}] at @s run summon tcmb:tcmb_starter ^1^^
execute as @s[type=tcmb:tcmb_car,tag=b4,tag=!backward,scores={speed=108..109}] at @s run summon tcmb:tcmb_starter ^1^^
execute as @s[type=tcmb:tcmb_car,tag=b3,tag=!backward,scores={speed=108..109}] at @s run summon tcmb:tcmb_starter ^1^^
execute as @s[type=tcmb:tcmb_car,tag=b2,tag=!backward,scores={speed=108..109}] at @s run summon tcmb:tcmb_starter ^1^^
execute as @s[type=tcmb:tcmb_car,tag=b1,tag=!backward,scores={speed=108..109}] at @s run summon tcmb:tcmb_starter ^1^^
execute as @s[type=tcmb:tcmb_car,tag=n,tag=!backward,scores={speed=108..109}] at @s run summon tcmb:tcmb_starter ^1^^
execute as @s[type=tcmb:tcmb_car,tag=eb,tag=backward,scores={speed=108..109}] at @s run summon tcmb:tcmb_starter ^-1^^
execute as @s[type=tcmb:tcmb_car,tag=b7,tag=backward,scores={speed=108..109}] at @s run summon tcmb:tcmb_starter ^-1^^
execute as @s[type=tcmb:tcmb_car,tag=b6,tag=backward,scores={speed=108..109}] at @s run summon tcmb:tcmb_starter ^-1^^
execute as @s[type=tcmb:tcmb_car,tag=b5,tag=backward,scores={speed=108..109}] at @s run summon tcmb:tcmb_starter ^-1^^
execute as @s[type=tcmb:tcmb_car,tag=b4,tag=backward,scores={speed=108..109}] at @s run summon tcmb:tcmb_starter ^-1^^
execute as @s[type=tcmb:tcmb_car,tag=b3,tag=backward,scores={speed=108..109}] at @s run summon tcmb:tcmb_starter ^-1^^
execute as @s[type=tcmb:tcmb_car,tag=b2,tag=backward,scores={speed=108..109}] at @s run summon tcmb:tcmb_starter ^-1^^
execute as @s[type=tcmb:tcmb_car,tag=b1,tag=backward,scores={speed=108..109}] at @s run summon tcmb:tcmb_starter ^-1^^
execute as @s[type=tcmb:tcmb_car,tag=n,tag=backward,scores={speed=108..109}] at @s run summon tcmb:tcmb_starter ^-1^^
scoreboard players remove @s[type=tcmb:tcmb_car,scores={speed=1..}] speed 1