<<<<<<< HEAD
execute as @e[type=tcmb:tcmb_car,scores={speed=0},tag=!stopping] at @s run event entity @e[r=2] 0km 
execute as @e[type=tcmb:tcmb_car,scores={speed=1}] at @s run event entity @e[r=2] 1km
execute as @e[type=tcmb:tcmb_car,scores={speed=2}] at @s run event entity @e[r=2] 2km
execute as @e[type=tcmb:tcmb_car,scores={speed=3}] at @s run event entity @e[r=2] 3km
execute as @e[type=tcmb:tcmb_car,scores={speed=4}] at @s run event entity @e[r=2] 4km
execute as @e[type=tcmb:tcmb_car,scores={speed=5}] at @s run event entity @e[r=2] 5km
execute as @e[type=tcmb:tcmb_car,scores={speed=6}] at @s run event entity @e[r=2] 6km
execute as @e[type=tcmb:tcmb_car,scores={speed=7}] at @s run event entity @e[r=2] 7km
execute as @e[type=tcmb:tcmb_car,scores={speed=8}] at @s run event entity @e[r=2] 8km
execute as @e[type=tcmb:tcmb_car,scores={speed=9}] at @s run event entity @e[r=2] 9km
execute as @e[type=tcmb:tcmb_car,scores={speed=10}] at @s run event entity @e[r=2] 10km
execute as @e[type=tcmb:tcmb_car,scores={speed=11}] at @s run event entity @e[r=2] 11km
execute as @e[type=tcmb:tcmb_car,scores={speed=12}] at @s run event entity @e[r=2] 12km
execute as @e[type=tcmb:tcmb_car,scores={speed=13}] at @s run event entity @e[r=2] 13km
execute as @e[type=tcmb:tcmb_car,scores={speed=14}] at @s run event entity @e[r=2] 14km
execute as @e[type=tcmb:tcmb_car,scores={speed=15}] at @s run event entity @e[r=2] 15km
execute as @e[type=tcmb:tcmb_car,scores={speed=16}] at @s run event entity @e[r=2] 16km
execute as @e[type=tcmb:tcmb_car,scores={speed=17}] at @s run event entity @e[r=2] 17km
execute as @e[type=tcmb:tcmb_car,scores={speed=18}] at @s run event entity @e[r=2] 18km
execute as @e[type=tcmb:tcmb_car,scores={speed=19}] at @s run event entity @e[r=2] 19km
execute as @e[type=tcmb:tcmb_car,scores={speed=20}] at @s run event entity @e[r=2] 20km
execute as @e[type=tcmb:tcmb_car,scores={speed=21}] at @s run event entity @e[r=2] 21km
execute as @e[type=tcmb:tcmb_car,scores={speed=22}] at @s run event entity @e[r=2] 22km
execute as @e[type=tcmb:tcmb_car,scores={speed=23}] at @s run event entity @e[r=2] 23km
execute as @e[type=tcmb:tcmb_car,scores={speed=24}] at @s run event entity @e[r=2] 24km
execute as @e[type=tcmb:tcmb_car,scores={speed=25}] at @s run event entity @e[r=2] 25km
execute as @e[type=tcmb:tcmb_car,scores={speed=26}] at @s run event entity @e[r=2] 26km
execute as @e[type=tcmb:tcmb_car,scores={speed=27}] at @s run event entity @e[r=2] 27km
execute as @e[type=tcmb:tcmb_car,scores={speed=28}] at @s run event entity @e[r=2] 28km
execute as @e[type=tcmb:tcmb_car,scores={speed=29}] at @s run event entity @e[r=2] 29km
execute as @e[type=tcmb:tcmb_car,scores={speed=30}] at @s run event entity @e[r=2] 30km
execute as @e[type=tcmb:tcmb_car,scores={speed=31}] at @s run event entity @e[r=2] 31km
execute as @e[type=tcmb:tcmb_car,scores={speed=32}] at @s run event entity @e[r=2] 32km
execute as @e[type=tcmb:tcmb_car,scores={speed=33}] at @s run event entity @e[r=2] 33km
execute as @e[type=tcmb:tcmb_car,scores={speed=34}] at @s run event entity @e[r=2] 34km
execute as @e[type=tcmb:tcmb_car,scores={speed=35}] at @s run event entity @e[r=2] 35km
execute as @e[type=tcmb:tcmb_car,scores={speed=36}] at @s run event entity @e[r=2] 36km
execute as @e[type=tcmb:tcmb_car,scores={speed=37}] at @s run event entity @e[r=2] 37km
execute as @e[type=tcmb:tcmb_car,scores={speed=38}] at @s run event entity @e[r=2] 38km
execute as @e[type=tcmb:tcmb_car,scores={speed=39}] at @s run event entity @e[r=2] 39km
execute as @e[type=tcmb:tcmb_car,scores={speed=40}] at @s run event entity @e[r=2] 40km
execute as @e[type=tcmb:tcmb_car,scores={speed=41}] at @s run event entity @e[r=2] 41km
execute as @e[type=tcmb:tcmb_car,scores={speed=42}] at @s run event entity @e[r=2] 42km
execute as @e[type=tcmb:tcmb_car,scores={speed=43}] at @s run event entity @e[r=2] 43km
execute as @e[type=tcmb:tcmb_car,scores={speed=44}] at @s run event entity @e[r=2] 44km
execute as @e[type=tcmb:tcmb_car,scores={speed=45}] at @s run event entity @e[r=2] 45km
execute as @e[type=tcmb:tcmb_car,scores={speed=46}] at @s run event entity @e[r=2] 46km
execute as @e[type=tcmb:tcmb_car,scores={speed=47}] at @s run event entity @e[r=2] 47km
execute as @e[type=tcmb:tcmb_car,scores={speed=48}] at @s run event entity @e[r=2] 48km
execute as @e[type=tcmb:tcmb_car,scores={speed=49}] at @s run event entity @e[r=2] 49km
execute as @e[type=tcmb:tcmb_car,scores={speed=50}] at @s run event entity @e[r=2] 50km
execute as @e[type=tcmb:tcmb_car,scores={speed=51}] at @s run event entity @e[r=2] 51km
execute as @e[type=tcmb:tcmb_car,scores={speed=52}] at @s run event entity @e[r=2] 52km
execute as @e[type=tcmb:tcmb_car,scores={speed=53}] at @s run event entity @e[r=2] 53km
execute as @e[type=tcmb:tcmb_car,scores={speed=54}] at @s run event entity @e[r=2] 54km
execute as @e[type=tcmb:tcmb_car,scores={speed=55}] at @s run event entity @e[r=2] 55km
execute as @e[type=tcmb:tcmb_car,scores={speed=56}] at @s run event entity @e[r=2] 56km
execute as @e[type=tcmb:tcmb_car,scores={speed=57}] at @s run event entity @e[r=2] 57km
execute as @e[type=tcmb:tcmb_car,scores={speed=58}] at @s run event entity @e[r=2] 58km
execute as @e[type=tcmb:tcmb_car,scores={speed=59}] at @s run event entity @e[r=2] 59km
execute as @e[type=tcmb:tcmb_car,scores={speed=60}] at @s run event entity @e[r=2] 60km
execute as @e[type=tcmb:tcmb_car,scores={speed=61}] at @s run event entity @e[r=2] 61km
execute as @e[type=tcmb:tcmb_car,scores={speed=62}] at @s run event entity @e[r=2] 62km
execute as @e[type=tcmb:tcmb_car,scores={speed=63}] at @s run event entity @e[r=2] 63km
execute as @e[type=tcmb:tcmb_car,scores={speed=64}] at @s run event entity @e[r=2] 64km
execute as @e[type=tcmb:tcmb_car,scores={speed=65}] at @s run event entity @e[r=2] 65km
execute as @e[type=tcmb:tcmb_car,scores={speed=66}] at @s run event entity @e[r=2] 66km
execute as @e[type=tcmb:tcmb_car,scores={speed=67}] at @s run event entity @e[r=2] 67km
execute as @e[type=tcmb:tcmb_car,scores={speed=68}] at @s run event entity @e[r=2] 68km
execute as @e[type=tcmb:tcmb_car,scores={speed=69}] at @s run event entity @e[r=2] 69km
execute as @e[type=tcmb:tcmb_car,scores={speed=70}] at @s run event entity @e[r=2] 70km
execute as @e[type=tcmb:tcmb_car,scores={speed=71}] at @s run event entity @e[r=2] 71km
execute as @e[type=tcmb:tcmb_car,scores={speed=72}] at @s run event entity @e[r=2] 72km
execute as @e[type=tcmb:tcmb_car,scores={speed=73}] at @s run event entity @e[r=2] 73km
execute as @e[type=tcmb:tcmb_car,scores={speed=74}] at @s run event entity @e[r=2] 74km
execute as @e[type=tcmb:tcmb_car,scores={speed=75}] at @s run event entity @e[r=2] 75km
execute as @e[type=tcmb:tcmb_car,scores={speed=76}] at @s run event entity @e[r=2] 76km
execute as @e[type=tcmb:tcmb_car,scores={speed=77}] at @s run event entity @e[r=2] 77km
execute as @e[type=tcmb:tcmb_car,scores={speed=78}] at @s run event entity @e[r=2] 78km
execute as @e[type=tcmb:tcmb_car,scores={speed=79}] at @s run event entity @e[r=2] 79km
execute as @e[type=tcmb:tcmb_car,scores={speed=80}] at @s run event entity @e[r=2] 80km
execute as @e[type=tcmb:tcmb_car,scores={speed=81}] at @s run event entity @e[r=2] 81km
execute as @e[type=tcmb:tcmb_car,scores={speed=82}] at @s run event entity @e[r=2] 82km
execute as @e[type=tcmb:tcmb_car,scores={speed=83}] at @s run event entity @e[r=2] 83km
execute as @e[type=tcmb:tcmb_car,scores={speed=84}] at @s run event entity @e[r=2] 84km
execute as @e[type=tcmb:tcmb_car,scores={speed=85}] at @s run event entity @e[r=2] 85km
execute as @e[type=tcmb:tcmb_car,scores={speed=86}] at @s run event entity @e[r=2] 86km
execute as @e[type=tcmb:tcmb_car,scores={speed=87}] at @s run event entity @e[r=2] 87km
execute as @e[type=tcmb:tcmb_car,scores={speed=88}] at @s run event entity @e[r=2] 88km
execute as @e[type=tcmb:tcmb_car,scores={speed=89}] at @s run event entity @e[r=2] 89km
execute as @e[type=tcmb:tcmb_car,scores={speed=90}] at @s run event entity @e[r=2] 90km
execute as @e[type=tcmb:tcmb_car,scores={speed=91}] at @s run event entity @e[r=2] 91km
execute as @e[type=tcmb:tcmb_car,scores={speed=92}] at @s run event entity @e[r=2] 92km
execute as @e[type=tcmb:tcmb_car,scores={speed=93}] at @s run event entity @e[r=2] 93km
execute as @e[type=tcmb:tcmb_car,scores={speed=94}] at @s run event entity @e[r=2] 94km
execute as @e[type=tcmb:tcmb_car,scores={speed=95}] at @s run event entity @e[r=2] 95km
execute as @e[type=tcmb:tcmb_car,scores={speed=96}] at @s run event entity @e[r=2] 96km
execute as @e[type=tcmb:tcmb_car,scores={speed=97}] at @s run event entity @e[r=2] 97km
execute as @e[type=tcmb:tcmb_car,scores={speed=98}] at @s run event entity @e[r=2] 98km
execute as @e[type=tcmb:tcmb_car,scores={speed=99}] at @s run event entity @e[r=2] 99km
execute as @e[type=tcmb:tcmb_car,scores={speed=100}] at @s run event entity @e[r=2] 100km
execute as @e[type=tcmb:tcmb_car,scores={speed=101}] at @s run event entity @e[r=2] 101km
execute as @e[type=tcmb:tcmb_car,scores={speed=102}] at @s run event entity @e[r=2] 102km
execute as @e[type=tcmb:tcmb_car,scores={speed=103}] at @s run event entity @e[r=2] 103km
execute as @e[type=tcmb:tcmb_car,scores={speed=104}] at @s run event entity @e[r=2] 104km
execute as @e[type=tcmb:tcmb_car,scores={speed=105}] at @s run event entity @e[r=2] 105km
execute as @e[type=tcmb:tcmb_car,scores={speed=106}] at @s run event entity @e[r=2] 106km
execute as @e[type=tcmb:tcmb_car,scores={speed=107}] at @s run event entity @e[r=2] 107km
execute as @e[type=tcmb:tcmb_car,scores={speed=108}] at @s run event entity @e[r=2] 108km
execute as @e[type=tcmb:tcmb_car,scores={speed=109}] at @s run event entity @e[r=2] 109km
execute as @e[type=tcmb:tcmb_car,scores={speed=110}] at @s run event entity @e[r=2] 110km
execute as @e[type=tcmb:tcmb_car,scores={speed=111}] at @s run event entity @e[r=2] 111km
execute as @e[type=tcmb:tcmb_car,scores={speed=112}] at @s run event entity @e[r=2] 112km
execute as @e[type=tcmb:tcmb_car,scores={speed=113}] at @s run event entity @e[r=2] 113km
execute as @e[type=tcmb:tcmb_car,scores={speed=114}] at @s run event entity @e[r=2] 114km
execute as @e[type=tcmb:tcmb_car,scores={speed=115}] at @s run event entity @e[r=2] 115km
execute as @e[type=tcmb:tcmb_car,scores={speed=116}] at @s run event entity @e[r=2] 116km
execute as @e[type=tcmb:tcmb_car,scores={speed=117}] at @s run event entity @e[r=2] 117km
execute as @e[type=tcmb:tcmb_car,scores={speed=118}] at @s run event entity @e[r=2] 118km
execute as @e[type=tcmb:tcmb_car,scores={speed=119}] at @s run event entity @e[r=2] 119km
execute as @e[type=tcmb:tcmb_car,scores={speed=120}] at @s run event entity @e[r=2] 120km
execute as @e[type=tcmb:tcmb_car,scores={speed=121}] at @s run event entity @e[r=2] 121km
execute as @e[type=tcmb:tcmb_car,scores={speed=122}] at @s run event entity @e[r=2] 122km
execute as @e[type=tcmb:tcmb_car,scores={speed=123}] at @s run event entity @e[r=2] 123km
execute as @e[type=tcmb:tcmb_car,scores={speed=124}] at @s run event entity @e[r=2] 124km
execute as @e[type=tcmb:tcmb_car,scores={speed=125}] at @s run event entity @e[r=2] 125km
execute as @e[type=tcmb:tcmb_car,scores={speed=126}] at @s run event entity @e[r=2] 126km
execute as @e[type=tcmb:tcmb_car,scores={speed=127}] at @s run event entity @e[r=2] 127km
execute as @e[type=tcmb:tcmb_car,scores={speed=128}] at @s run event entity @e[r=2] 128km
execute as @e[type=tcmb:tcmb_car,scores={speed=129}] at @s run event entity @e[r=2] 129km
execute as @e[type=tcmb:tcmb_car,scores={speed=130}] at @s run event entity @e[r=2] 130km
execute as @e[type=tcmb:tcmb_car,scores={speed=131}] at @s run event entity @e[r=2] 131km
execute as @e[type=tcmb:tcmb_car,scores={speed=132}] at @s run event entity @e[r=2] 132km
execute as @e[type=tcmb:tcmb_car,scores={speed=133}] at @s run event entity @e[r=2] 133km
execute as @e[type=tcmb:tcmb_car,scores={speed=134}] at @s run event entity @e[r=2] 134km
execute as @e[type=tcmb:tcmb_car,scores={speed=135}] at @s run event entity @e[r=2] 135km
execute as @e[type=tcmb:tcmb_car,scores={speed=136}] at @s run event entity @e[r=2] 136km
execute as @e[type=tcmb:tcmb_car,scores={speed=137}] at @s run event entity @e[r=2] 137km
execute as @e[type=tcmb:tcmb_car,scores={speed=138}] at @s run event entity @e[r=2] 138km
execute as @e[type=tcmb:tcmb_car,scores={speed=139}] at @s run event entity @e[r=2] 139km
execute as @e[type=tcmb:tcmb_car,scores={speed=140}] at @s run event entity @e[r=2] 140km
execute as @e[type=tcmb:tcmb_car,scores={speed=141}] at @s run event entity @e[r=2] 141km
execute as @e[type=tcmb:tcmb_car,scores={speed=142}] at @s run event entity @e[r=2] 142km
execute as @e[type=tcmb:tcmb_car,scores={speed=143}] at @s run event entity @e[r=2] 143km
execute as @e[type=tcmb:tcmb_car,scores={speed=144}] at @s run event entity @e[r=2] 144km
execute as @e[type=tcmb:tcmb_car,scores={speed=145}] at @s run event entity @e[r=2] 145km
execute as @e[type=tcmb:tcmb_car,scores={speed=146}] at @s run event entity @e[r=2] 146km
execute as @e[type=tcmb:tcmb_car,scores={speed=147}] at @s run event entity @e[r=2] 147km
execute as @e[type=tcmb:tcmb_car,scores={speed=148}] at @s run event entity @e[r=2] 148km
execute as @e[type=tcmb:tcmb_car,scores={speed=149}] at @s run event entity @e[r=2] 149km
execute as @e[type=tcmb:tcmb_car,scores={speed=150}] at @s run event entity @e[r=2] 150km
execute as @e[type=tcmb:tcmb_car,scores={speed=151}] at @s run event entity @e[r=2] 151km
execute as @e[type=tcmb:tcmb_car,scores={speed=152}] at @s run event entity @e[r=2] 152km
execute as @e[type=tcmb:tcmb_car,scores={speed=153}] at @s run event entity @e[r=2] 153km
execute as @e[type=tcmb:tcmb_car,scores={speed=154}] at @s run event entity @e[r=2] 154km
execute as @e[type=tcmb:tcmb_car,scores={speed=155}] at @s run event entity @e[r=2] 155km
execute as @e[type=tcmb:tcmb_car,scores={speed=156}] at @s run event entity @e[r=2] 156km
execute as @e[type=tcmb:tcmb_car,scores={speed=157}] at @s run event entity @e[r=2] 157km
execute as @e[type=tcmb:tcmb_car,scores={speed=158}] at @s run event entity @e[r=2] 158km
execute as @e[type=tcmb:tcmb_car,scores={speed=159}] at @s run event entity @e[r=2] 159km
execute as @e[type=tcmb:tcmb_car,scores={speed=160}] at @s run event entity @e[r=2] 160km
execute as @e[type=tcmb:tcmb_car,scores={speed=161}] at @s run event entity @e[r=2] 161km
execute as @e[type=tcmb:tcmb_car,scores={speed=162}] at @s run event entity @e[r=2] 162km
execute as @e[type=tcmb:tcmb_car,scores={speed=163}] at @s run event entity @e[r=2] 163km
execute as @e[type=tcmb:tcmb_car,scores={speed=164}] at @s run event entity @e[r=2] 164km
execute as @e[type=tcmb:tcmb_car,scores={speed=165}] at @s run event entity @e[r=2] 165km
execute as @e[type=tcmb:tcmb_car,scores={speed=166}] at @s run event entity @e[r=2] 166km
execute as @e[type=tcmb:tcmb_car,scores={speed=167}] at @s run event entity @e[r=2] 167km
execute as @e[type=tcmb:tcmb_car,scores={speed=168}] at @s run event entity @e[r=2] 168km
execute as @e[type=tcmb:tcmb_car,scores={speed=169}] at @s run event entity @e[r=2] 169km
execute as @e[type=tcmb:tcmb_car,scores={speed=170}] at @s run event entity @e[r=2] 170km
execute as @e[type=tcmb:tcmb_car,scores={speed=171}] at @s run event entity @e[r=2] 171km
execute as @e[type=tcmb:tcmb_car,scores={speed=172}] at @s run event entity @e[r=2] 172km
execute as @e[type=tcmb:tcmb_car,scores={speed=173}] at @s run event entity @e[r=2] 173km
execute as @e[type=tcmb:tcmb_car,scores={speed=174}] at @s run event entity @e[r=2] 174km
execute as @e[type=tcmb:tcmb_car,scores={speed=175}] at @s run event entity @e[r=2] 175km
execute as @e[type=tcmb:tcmb_car,scores={speed=176}] at @s run event entity @e[r=2] 176km
execute as @e[type=tcmb:tcmb_car,scores={speed=177}] at @s run event entity @e[r=2] 177km
execute as @e[type=tcmb:tcmb_car,scores={speed=178}] at @s run event entity @e[r=2] 178km
execute as @e[type=tcmb:tcmb_car,scores={speed=179}] at @s run event entity @e[r=2] 179km
execute as @e[type=tcmb:tcmb_car,scores={speed=180}] at @s run event entity @e[r=2] 180km
execute as @e[type=tcmb:tcmb_car,scores={speed=181}] at @s run event entity @e[r=2] 181km
execute as @e[type=tcmb:tcmb_car,scores={speed=182}] at @s run event entity @e[r=2] 182km
execute as @e[type=tcmb:tcmb_car,scores={speed=183}] at @s run event entity @e[r=2] 183km
execute as @e[type=tcmb:tcmb_car,scores={speed=184}] at @s run event entity @e[r=2] 184km
execute as @e[type=tcmb:tcmb_car,scores={speed=185}] at @s run event entity @e[r=2] 185km
execute as @e[type=tcmb:tcmb_car,scores={speed=186}] at @s run event entity @e[r=2] 186km
execute as @e[type=tcmb:tcmb_car,scores={speed=187}] at @s run event entity @e[r=2] 187km
execute as @e[type=tcmb:tcmb_car,scores={speed=188}] at @s run event entity @e[r=2] 188km
execute as @e[type=tcmb:tcmb_car,scores={speed=189}] at @s run event entity @e[r=2] 189km
execute as @e[type=tcmb:tcmb_car,scores={speed=190}] at @s run event entity @e[r=2] 190km
execute as @e[type=tcmb:tcmb_car,scores={speed=191}] at @s run event entity @e[r=2] 191km
execute as @e[type=tcmb:tcmb_car,scores={speed=192}] at @s run event entity @e[r=2] 192km
execute as @e[type=tcmb:tcmb_car,scores={speed=193}] at @s run event entity @e[r=2] 193km
execute as @e[type=tcmb:tcmb_car,scores={speed=194}] at @s run event entity @e[r=2] 194km
execute as @e[type=tcmb:tcmb_car,scores={speed=195}] at @s run event entity @e[r=2] 195km
execute as @e[type=tcmb:tcmb_car,scores={speed=196}] at @s run event entity @e[r=2] 196km
execute as @e[type=tcmb:tcmb_car,scores={speed=197}] at @s run event entity @e[r=2] 197km
execute as @e[type=tcmb:tcmb_car,scores={speed=198}] at @s run event entity @e[r=2] 198km
execute as @e[type=tcmb:tcmb_car,scores={speed=199}] at @s run event entity @e[r=2] 199km
execute as @e[type=tcmb:tcmb_car,scores={speed=200}] at @s run event entity @e[r=2] 200km
execute as @e[type=tcmb:tcmb_car,scores={speed=201}] at @s run event entity @e[r=2] 201km
execute as @e[type=tcmb:tcmb_car,scores={speed=202}] at @s run event entity @e[r=2] 202km
execute as @e[type=tcmb:tcmb_car,scores={speed=203}] at @s run event entity @e[r=2] 203km
execute as @e[type=tcmb:tcmb_car,scores={speed=204}] at @s run event entity @e[r=2] 204km
execute as @e[type=tcmb:tcmb_car,scores={speed=205}] at @s run event entity @e[r=2] 205km
execute as @e[type=tcmb:tcmb_car,scores={speed=206}] at @s run event entity @e[r=2] 206km
execute as @e[type=tcmb:tcmb_car,scores={speed=207}] at @s run event entity @e[r=2] 207km
execute as @e[type=tcmb:tcmb_car,scores={speed=208}] at @s run event entity @e[r=2] 208km
execute as @e[type=tcmb:tcmb_car,scores={speed=209}] at @s run event entity @e[r=2] 209km
execute as @e[type=tcmb:tcmb_car,scores={speed=210}] at @s run event entity @e[r=2] 210km
execute as @e[type=tcmb:tcmb_car,scores={speed=211}] at @s run event entity @e[r=2] 211km
execute as @e[type=tcmb:tcmb_car,scores={speed=212}] at @s run event entity @e[r=2] 212km
execute as @e[type=tcmb:tcmb_car,scores={speed=213}] at @s run event entity @e[r=2] 213km
execute as @e[type=tcmb:tcmb_car,scores={speed=214}] at @s run event entity @e[r=2] 214km
execute as @e[type=tcmb:tcmb_car,scores={speed=215}] at @s run event entity @e[r=2] 215km
execute as @e[type=tcmb:tcmb_car,scores={speed=216}] at @s run event entity @e[r=2] 216km
execute as @e[type=tcmb:tcmb_car,scores={speed=217}] at @s run event entity @e[r=2] 217km
execute as @e[type=tcmb:tcmb_car,scores={speed=218}] at @s run event entity @e[r=2] 218km
execute as @e[type=tcmb:tcmb_car,scores={speed=219}] at @s run event entity @e[r=2] 219km
execute as @e[type=tcmb:tcmb_car,scores={speed=220}] at @s run event entity @e[r=2] 220km
execute as @e[type=tcmb:tcmb_car,scores={speed=221}] at @s run event entity @e[r=2] 221km
execute as @e[type=tcmb:tcmb_car,scores={speed=222}] at @s run event entity @e[r=2] 222km
execute as @e[type=tcmb:tcmb_car,scores={speed=223}] at @s run event entity @e[r=2] 223km
execute as @e[type=tcmb:tcmb_car,scores={speed=224}] at @s run event entity @e[r=2] 224km
execute as @e[type=tcmb:tcmb_car,scores={speed=225}] at @s run event entity @e[r=2] 225km
execute as @e[type=tcmb:tcmb_car,scores={speed=226}] at @s run event entity @e[r=2] 226km
execute as @e[type=tcmb:tcmb_car,scores={speed=227}] at @s run event entity @e[r=2] 227km
execute as @e[type=tcmb:tcmb_car,scores={speed=228}] at @s run event entity @e[r=2] 228km
execute as @e[type=tcmb:tcmb_car,scores={speed=229}] at @s run event entity @e[r=2] 229km
execute as @e[type=tcmb:tcmb_car,scores={speed=230}] at @s run event entity @e[r=2] 230km
execute as @e[type=tcmb:tcmb_car,scores={speed=231}] at @s run event entity @e[r=2] 231km
execute as @e[type=tcmb:tcmb_car,scores={speed=232}] at @s run event entity @e[r=2] 232km
execute as @e[type=tcmb:tcmb_car,scores={speed=233}] at @s run event entity @e[r=2] 233km
execute as @e[type=tcmb:tcmb_car,scores={speed=234}] at @s run event entity @e[r=2] 234km
execute as @e[type=tcmb:tcmb_car,scores={speed=235}] at @s run event entity @e[r=2] 235km
execute as @e[type=tcmb:tcmb_car,scores={speed=236}] at @s run event entity @e[r=2] 236km
execute as @e[type=tcmb:tcmb_car,scores={speed=237}] at @s run event entity @e[r=2] 237km
execute as @e[type=tcmb:tcmb_car,scores={speed=238}] at @s run event entity @e[r=2] 238km
execute as @e[type=tcmb:tcmb_car,scores={speed=239}] at @s run event entity @e[r=2] 239km
execute as @e[type=tcmb:tcmb_car,scores={speed=240}] at @s run event entity @e[r=2] 240km
execute as @e[type=tcmb:tcmb_car,scores={speed=241}] at @s run event entity @e[r=2] 241km
execute as @e[type=tcmb:tcmb_car,scores={speed=242}] at @s run event entity @e[r=2] 242km
execute as @e[type=tcmb:tcmb_car,scores={speed=243}] at @s run event entity @e[r=2] 243km
execute as @e[type=tcmb:tcmb_car,scores={speed=244}] at @s run event entity @e[r=2] 244km
execute as @e[type=tcmb:tcmb_car,scores={speed=245}] at @s run event entity @e[r=2] 245km
execute as @e[type=tcmb:tcmb_car,scores={speed=246}] at @s run event entity @e[r=2] 246km
execute as @e[type=tcmb:tcmb_car,scores={speed=247}] at @s run event entity @e[r=2] 247km
execute as @e[type=tcmb:tcmb_car,scores={speed=248}] at @s run event entity @e[r=2] 248km
execute as @e[type=tcmb:tcmb_car,scores={speed=249}] at @s run event entity @e[r=2] 249km
execute as @e[type=tcmb:tcmb_car,scores={speed=250}] at @s run event entity @e[r=2] 250km
execute as @e[type=tcmb:tcmb_car,scores={speed=251}] at @s run event entity @e[r=2] 251km
execute as @e[type=tcmb:tcmb_car,scores={speed=252}] at @s run event entity @e[r=2] 252km
execute as @e[type=tcmb:tcmb_car,scores={speed=253}] at @s run event entity @e[r=2] 253km
execute as @e[type=tcmb:tcmb_car,scores={speed=254}] at @s run event entity @e[r=2] 254km
execute as @e[type=tcmb:tcmb_car,scores={speed=255}] at @s run event entity @e[r=2] 255km
execute as @e[type=tcmb:tcmb_car,scores={speed=256}] at @s run event entity @e[r=2] 256km
execute as @e[type=tcmb:tcmb_car,scores={speed=257}] at @s run event entity @e[r=2] 257km
execute as @e[type=tcmb:tcmb_car,scores={speed=258}] at @s run event entity @e[r=2] 258km
execute as @e[type=tcmb:tcmb_car,scores={speed=259}] at @s run event entity @e[r=2] 259km
execute as @e[type=tcmb:tcmb_car,scores={speed=260}] at @s run event entity @e[r=2] 260km
execute as @e[type=tcmb:tcmb_car,scores={speed=261}] at @s run event entity @e[r=2] 261km
execute as @e[type=tcmb:tcmb_car,scores={speed=262}] at @s run event entity @e[r=2] 262km
execute as @e[type=tcmb:tcmb_car,scores={speed=263}] at @s run event entity @e[r=2] 263km
execute as @e[type=tcmb:tcmb_car,scores={speed=264}] at @s run event entity @e[r=2] 264km
execute as @e[type=tcmb:tcmb_car,scores={speed=265}] at @s run event entity @e[r=2] 265km
execute as @e[type=tcmb:tcmb_car,scores={speed=266}] at @s run event entity @e[r=2] 266km
execute as @e[type=tcmb:tcmb_car,scores={speed=267}] at @s run event entity @e[r=2] 267km
execute as @e[type=tcmb:tcmb_car,scores={speed=268}] at @s run event entity @e[r=2] 268km
execute as @e[type=tcmb:tcmb_car,scores={speed=269}] at @s run event entity @e[r=2] 269km
execute as @e[type=tcmb:tcmb_car,scores={speed=270}] at @s run event entity @e[r=2] 270km
execute as @e[type=tcmb:tcmb_car,scores={speed=271}] at @s run event entity @e[r=2] 271km
execute as @e[type=tcmb:tcmb_car,scores={speed=272}] at @s run event entity @e[r=2] 272km
execute as @e[type=tcmb:tcmb_car,scores={speed=273}] at @s run event entity @e[r=2] 273km
execute as @e[type=tcmb:tcmb_car,scores={speed=274}] at @s run event entity @e[r=2] 274km
execute as @e[type=tcmb:tcmb_car,scores={speed=275}] at @s run event entity @e[r=2] 275km
execute as @e[type=tcmb:tcmb_car,scores={speed=276}] at @s run event entity @e[r=2] 276km
execute as @e[type=tcmb:tcmb_car,scores={speed=277}] at @s run event entity @e[r=2] 277km
execute as @e[type=tcmb:tcmb_car,scores={speed=278}] at @s run event entity @e[r=2] 278km
execute as @e[type=tcmb:tcmb_car,scores={speed=279}] at @s run event entity @e[r=2] 279km
execute as @e[type=tcmb:tcmb_car,scores={speed=280}] at @s run event entity @e[r=2] 280km
execute as @e[type=tcmb:tcmb_car,scores={speed=281}] at @s run event entity @e[r=2] 281km
execute as @e[type=tcmb:tcmb_car,scores={speed=282}] at @s run event entity @e[r=2] 282km
execute as @e[type=tcmb:tcmb_car,scores={speed=283}] at @s run event entity @e[r=2] 283km
execute as @e[type=tcmb:tcmb_car,scores={speed=284}] at @s run event entity @e[r=2] 284km
execute as @e[type=tcmb:tcmb_car,scores={speed=285}] at @s run event entity @e[r=2] 285km
execute as @e[type=tcmb:tcmb_car,scores={speed=286}] at @s run event entity @e[r=2] 286km
execute as @e[type=tcmb:tcmb_car,scores={speed=287}] at @s run event entity @e[r=2] 287km
execute as @e[type=tcmb:tcmb_car,scores={speed=288}] at @s run event entity @e[r=2] 288km
execute as @e[type=tcmb:tcmb_car,scores={speed=289}] at @s run event entity @e[r=2] 289km
execute as @e[type=tcmb:tcmb_car,scores={speed=290}] at @s run event entity @e[r=2] 290km
execute as @e[type=tcmb:tcmb_car,scores={speed=291}] at @s run event entity @e[r=2] 291km
execute as @e[type=tcmb:tcmb_car,scores={speed=292}] at @s run event entity @e[r=2] 292km
execute as @e[type=tcmb:tcmb_car,scores={speed=293}] at @s run event entity @e[r=2] 293km
execute as @e[type=tcmb:tcmb_car,scores={speed=294}] at @s run event entity @e[r=2] 294km
execute as @e[type=tcmb:tcmb_car,scores={speed=295}] at @s run event entity @e[r=2] 295km
execute as @e[type=tcmb:tcmb_car,scores={speed=296}] at @s run event entity @e[r=2] 296km
execute as @e[type=tcmb:tcmb_car,scores={speed=297}] at @s run event entity @e[r=2] 297km
execute as @e[type=tcmb:tcmb_car,scores={speed=298}] at @s run event entity @e[r=2] 298km
execute as @e[type=tcmb:tcmb_car,scores={speed=299}] at @s run event entity @e[r=2] 299km
execute as @e[type=tcmb:tcmb_car,scores={speed=300}] at @s run event entity @e[r=2] 300km
execute as @e[type=tcmb:tcmb_car,scores={speed=301}] at @s run event entity @e[r=2] 301km
execute as @e[type=tcmb:tcmb_car,scores={speed=302}] at @s run event entity @e[r=2] 302km
execute as @e[type=tcmb:tcmb_car,scores={speed=303}] at @s run event entity @e[r=2] 303km
execute as @e[type=tcmb:tcmb_car,scores={speed=304}] at @s run event entity @e[r=2] 304km
execute as @e[type=tcmb:tcmb_car,scores={speed=305}] at @s run event entity @e[r=2] 305km
execute as @e[type=tcmb:tcmb_car,scores={speed=306}] at @s run event entity @e[r=2] 306km
execute as @e[type=tcmb:tcmb_car,scores={speed=307}] at @s run event entity @e[r=2] 307km
execute as @e[type=tcmb:tcmb_car,scores={speed=308}] at @s run event entity @e[r=2] 308km
execute as @e[type=tcmb:tcmb_car,scores={speed=309}] at @s run event entity @e[r=2] 309km
execute as @e[type=tcmb:tcmb_car,scores={speed=310}] at @s run event entity @e[r=2] 310km
execute as @e[type=tcmb:tcmb_car,scores={speed=311}] at @s run event entity @e[r=2] 311km
execute as @e[type=tcmb:tcmb_car,scores={speed=312}] at @s run event entity @e[r=2] 312km
execute as @e[type=tcmb:tcmb_car,scores={speed=313}] at @s run event entity @e[r=2] 313km
execute as @e[type=tcmb:tcmb_car,scores={speed=314}] at @s run event entity @e[r=2] 314km
execute as @e[type=tcmb:tcmb_car,scores={speed=315}] at @s run event entity @e[r=2] 315km
execute as @e[type=tcmb:tcmb_car,scores={speed=316}] at @s run event entity @e[r=2] 316km
execute as @e[type=tcmb:tcmb_car,scores={speed=317}] at @s run event entity @e[r=2] 317km
execute as @e[type=tcmb:tcmb_car,scores={speed=318}] at @s run event entity @e[r=2] 318km
execute as @e[type=tcmb:tcmb_car,scores={speed=319}] at @s run event entity @e[r=2] 319km
execute as @e[type=tcmb:tcmb_car,scores={speed=320}] at @s run event entity @e[r=2] 320km
execute as @e[type=tcmb:tcmb_car,scores={speed=321}] at @s run event entity @e[r=2] 321km
execute as @e[type=tcmb:tcmb_car,scores={speed=322}] at @s run event entity @e[r=2] 322km
execute as @e[type=tcmb:tcmb_car,scores={speed=323}] at @s run event entity @e[r=2] 323km
execute as @e[type=tcmb:tcmb_car,scores={speed=324}] at @s run event entity @e[r=2] 324km
execute as @e[type=tcmb:tcmb_car,scores={speed=325}] at @s run event entity @e[r=2] 325km
execute as @e[type=tcmb:tcmb_car,scores={speed=326}] at @s run event entity @e[r=2] 326km
execute as @e[type=tcmb:tcmb_car,scores={speed=327}] at @s run event entity @e[r=2] 327km
execute as @e[type=tcmb:tcmb_car,scores={speed=328}] at @s run event entity @e[r=2] 328km
execute as @e[type=tcmb:tcmb_car,scores={speed=329}] at @s run event entity @e[r=2] 329km
execute as @e[type=tcmb:tcmb_car,scores={speed=330}] at @s run event entity @e[r=2] 330km
execute as @e[type=tcmb:tcmb_car,scores={speed=331}] at @s run event entity @e[r=2] 331km
execute as @e[type=tcmb:tcmb_car,scores={speed=332}] at @s run event entity @e[r=2] 332km
execute as @e[type=tcmb:tcmb_car,scores={speed=333}] at @s run event entity @e[r=2] 333km
execute as @e[type=tcmb:tcmb_car,scores={speed=334}] at @s run event entity @e[r=2] 334km
execute as @e[type=tcmb:tcmb_car,scores={speed=335}] at @s run event entity @e[r=2] 335km
execute as @e[type=tcmb:tcmb_car,scores={speed=336}] at @s run event entity @e[r=2] 336km
execute as @e[type=tcmb:tcmb_car,scores={speed=337}] at @s run event entity @e[r=2] 337km
execute as @e[type=tcmb:tcmb_car,scores={speed=338}] at @s run event entity @e[r=2] 338km
execute as @e[type=tcmb:tcmb_car,scores={speed=339}] at @s run event entity @e[r=2] 339km
execute as @e[type=tcmb:tcmb_car,scores={speed=340}] at @s run event entity @e[r=2] 340km
execute as @e[type=tcmb:tcmb_car,scores={speed=341}] at @s run event entity @e[r=2] 341km
execute as @e[type=tcmb:tcmb_car,scores={speed=342}] at @s run event entity @e[r=2] 342km
execute as @e[type=tcmb:tcmb_car,scores={speed=343}] at @s run event entity @e[r=2] 343km
execute as @e[type=tcmb:tcmb_car,scores={speed=344}] at @s run event entity @e[r=2] 344km
execute as @e[type=tcmb:tcmb_car,scores={speed=345}] at @s run event entity @e[r=2] 345km
execute as @e[type=tcmb:tcmb_car,scores={speed=346}] at @s run event entity @e[r=2] 346km
execute as @e[type=tcmb:tcmb_car,scores={speed=347}] at @s run event entity @e[r=2] 347km
execute as @e[type=tcmb:tcmb_car,scores={speed=348}] at @s run event entity @e[r=2] 348km
execute as @e[type=tcmb:tcmb_car,scores={speed=349}] at @s run event entity @e[r=2] 349km
execute as @e[type=tcmb:tcmb_car,scores={speed=350}] at @s run event entity @e[r=2] 350km
execute as @e[type=tcmb:tcmb_car,scores={speed=351}] at @s run event entity @e[r=2] 351km
execute as @e[type=tcmb:tcmb_car,scores={speed=352}] at @s run event entity @e[r=2] 352km
execute as @e[type=tcmb:tcmb_car,scores={speed=353}] at @s run event entity @e[r=2] 353km
execute as @e[type=tcmb:tcmb_car,scores={speed=354}] at @s run event entity @e[r=2] 354km
execute as @e[type=tcmb:tcmb_car,scores={speed=355}] at @s run event entity @e[r=2] 355km
execute as @e[type=tcmb:tcmb_car,scores={speed=356}] at @s run event entity @e[r=2] 356km
execute as @e[type=tcmb:tcmb_car,scores={speed=357}] at @s run event entity @e[r=2] 357km
execute as @e[type=tcmb:tcmb_car,scores={speed=358}] at @s run event entity @e[r=2] 358km
execute as @e[type=tcmb:tcmb_car,scores={speed=359}] at @s run event entity @e[r=2] 359km
execute as @e[type=tcmb:tcmb_car,scores={speed=360}] at @s run event entity @e[r=2] 360km
=======
>>>>>>> main
execute as @e[type=tcmb:tcmb_car,tag=pt0] at @s run function curve/pt0
execute as @e[type=tcmb:tcmb_car,tag=pt1] at @s run function curve/pt1
execute as @e[type=tcmb:tcmb_car,tag=pt2] at @s run function curve/pt2