tag @e[type=tcmb:tcmb_car,c=1] remove eb
tag @e[type=tcmb:tcmb_car,c=1] remove b7
tag @e[type=tcmb:tcmb_car,c=1] remove b6
tag @e[type=tcmb:tcmb_car,c=1] remove b5
tag @e[type=tcmb:tcmb_car,c=1] remove b4
tag @e[type=tcmb:tcmb_car,c=1] remove b3
tag @e[type=tcmb:tcmb_car,c=1] remove b2
tag @e[type=tcmb:tcmb_car,c=1] remove b1
tag @e[type=tcmb:tcmb_car,c=1] remove n
tag @e[type=tcmb:tcmb_car,c=1] remove p1
tag @e[type=tcmb:tcmb_car,c=1] remove p2
tag @e[type=tcmb:tcmb_car,c=1] remove p3
tag @e[type=tcmb:tcmb_car,c=1] remove p4