execute as @e[tag=car1,r=1] at @s if block ^1^^17.5 rail run scriptevent tcmb_minecart_engine:rotate -3
execute as @e[tag=car1,r=1] at @s if block ^1^^17.5 golden_rail run scriptevent tcmb_minecart_engine:rotate -3
execute as @e[tag=car1,r=1] at @s if block ^1^^17.5 detector_rail run scriptevent tcmb_minecart_engine:rotate -3
execute as @e[tag=car1,r=1] at @s if block ^-1^^17.5 rail run scriptevent tcmb_minecart_engine:rotate 3
execute as @e[tag=car1,r=1] at @s if block ^-1^^17.5 golden_rail run scriptevent tcmb_minecart_engine:rotate 3
execute as @e[tag=car1,r=1] at @s if block ^-1^^17.5 detector_rail run scriptevent tcmb_minecart_engine:rotate 3
execute as @e[tag=car2,r=1] at @s if block ^-1^^-17.5 rail run scriptevent tcmb_minecart_engine:rotate -3
execute as @e[tag=car2,r=1] at @s if block ^-1^^-17.5 golden_rail run scriptevent tcmb_minecart_engine:rotate -3
execute as @e[tag=car2,r=1] at @s if block ^-1^^-17.5 detector_rail run scriptevent tcmb_minecart_engine:rotate -3
execute as @e[tag=car2,r=1] at @s if block ^1^^-17.5 rail run scriptevent tcmb_minecart_engine:rotate 3
execute as @e[tag=car2,r=1] at @s if block ^1^^-17.5 golden_rail run scriptevent tcmb_minecart_engine:rotate 3
execute as @e[tag=car2,r=1] at @s if block ^1^^-17.5 detector_rail run scriptevent tcmb_minecart_engine:rotate 3